#!/usr/bin/sh
clear
###############################################################################################
export LANG=fr_FR.UTF-8
export blue="\\033[1;34m"
export cyan="\\033[1;36m"
export green="\\033[1;32m"
export nc="\\033[0;39m"
export red="\\033[1;31m"
export white="\\033[1;37m"
export yellow="\\033[1;33m"

echo -e "$green ******************************************************************************"
echo -e "$green *                                                                            *"
echo -e "$green * [$red ARCHBOX$green ]                                                                *"									   				  
echo -e "$green * $cyan Votre console multimedia de salon$green                                         *"
echo -e "$green *                                                                            *"
echo -e "$green ******************************************************************************"
###############################################################################################


###############################################################################################
echo -e "$yellow"
echo -e "Choisissez votre programe : $nc"
LISTE=(" XBMC " " Bureau XFCE" " Emulateurs" " Terminal" " Eteindre")
select CHOIX in "${LISTE[@]}" ; do
case $REPLY in
        1|'&')
		echo -e "$yellow"
                echo -e "Lancement :$red" "XBMC... $nc"
                /usr/bin/xinit /usr/bin/xbmc-standalone -- :0 -nolisten tcp
        break
        ;;
        2|"é")
                echo -e "$yellow"
                echo -e "Lancement :$red" "Bureau XFCE... $nc"
                /usr/bin/startxfce4
        break
        ;;
        3|'"')
		echo -e "$yellow"
		echo -e "Choisissez votre$red" "Emulateurs $nc"
		LISTE2=(" Super Nintendo" " Nitendo64" " MegaDrive" " Steam" " Retour")
		select CHOIXEMUL in "${LISTE2[@]}" ; do
		case $REPLY in
			1|'&')
				echo -e "$yellow"
                		echo -e "Lancement :$red" "Super Nintendo... $nc"
				/usr/bin/xinit /usr/bin/zsnes -- :0 -nolisten tcp	
			break
			;;
			2|"é")
				echo -e "$yellow"
                		echo -e "Lancement :$red" "Nintendo64... $nc"
				/usr/bin/xinit /usr/bin/zsnes -- :0 -nolisten tcp
			break
			;;
			3|'"')
				echo -e "$yellow"
                		echo -e "Lancement :$red" "MegaDrive... $nc"
				/usr/bin/xinit /usr/bin/zsnes -- :0 -nolisten tcp
			break
        		;;
			4|"'")
				echo -e "$yellow"
                		echo -e "Lancement :$red" "Steam... $nc"
				/usr/bin/xinit /usr/bin/steam -- :0 -nolisten tcp
			break
        		;;
			5|'(')
				echo -e "$yellow"
                		echo -e "$red" "Retour... $nc"
				exec
			break
        		;;
			esac
		done
        break
        ;;
	4|"'")
                echo -e "$yellow"
                echo -e "Lancement :$red" "Terminal... $nc"
                /usr/bin/xinit /usr/bin/xterm -fullscreen -maximized xterm -fa "size=12:antialias=false" -rv
        break
        ;;
        *|"(")
                echo -e "$yellow"
                echo -e "Extinction de l'ordinateur... $nc"
                shutdown now
        break
        ;;
        esac
done
echo -e "$white ******************************************************************************"
###############################################################################################

