#!/usr/bin/sh
clear
###############################################################################################
export LANG=fr_FR.UTF-8
export blue="\\033[1;34m"
export cyan="\\033[1;36m"
export green="\\033[1;32m"
export nc="\\033[0;39m"
export red="\\033[1;31m"
export white="\\033[1;37m"
export yellow="\\033[1;33m"

echo -e "$green ******************************************************************************"
echo -e "$green *                                                                            *"
echo -e "$green * [$red ARCHBOX$green ]                                                                *"									   				  
echo -e "$green * $cyan Votre console multimedia de salon$green                                         *"
echo -e "$green *                                                                            *"
echo -e "$green ******************************************************************************"
###############################################################################################

echo " "
echo " "

###############################################################################################
echo -e "$green ******************************************************************************"
#echo -ne "$green   Ip: $yellow" ; ifconfig -a | grep inet | grep -v '127.0.0.1' | grep -v '::' | awk '{ print $2}'
echo -e "$green   SSH sur touriste:$yellow OK"
echo -e "$green ******************************************************************************"
###############################################################################################

echo " "
echo " "

###############################################################################################
echo -e "$white ******************************************************************************"
LISTE=(" Xbmc (defaut 3sc)" " Bureau XFCE" " Emulateurs" " Eteindre l'ordinateur")
select CHOIX in "${LISTE[@]}" ; do
case $REPLY in
        1|'&')
                echo -e "$yellow" "Lancement :" "$red" " XBMC... $nc"
                /usr/bin/xinit /usr/bin/xbmc-standalone -- :0 -nolisten tcp
        break
        ;;
        2|"é")
                echo -e "$yellow" "Lancement :" "$red" " Bureau XFCE... $nc"
                /usr/bin/startxfce4
        break
        ;;
        3|'"')
                echo -e "$yellow" "Lancement :" "$red" " Emulateurs... $nc"
        break
        ;;
        *|"'")
                echo -e "$yellow" "Extinction de l'ordinateur multimedia... $nc"
                shutdown
        break
        ;;
        esac
done
echo -e "$white ******************************************************************************"
###############################################################################################

